Repository ThisDotE/communityForDevelopers, pull requests merged in 2024-03, with the labels that each got.

#27 [Feature/study-article] 스터디 게시글 요소 출력 및 댓글 전체 출력
  src/main/java/org/thisdote/communityfordevelopers/article/ArticleDTO.java
  src/main/java/org/thisdote/communityfordevelopers/article/ArticleMapper.java
  src/main/java/org/thisdote/communityfordevelopers/article/ArticleService.java
  src/main/resources/org/thisdote/communityfordevelopers/article/ArticleMapper.xml
  src/test/java/org/thisdote/communityfordevelopers/article/ArticleTest.java
Labels: bug, enhancement

#29 [Feature/select-user-by-usercode] 스터디그룹, 회원등급 포함된 회원정보조회
  src/main/java/org/thisdote/communityfordevelopers/user/UserDTO.java
  src/main/java/org/thisdote/communityfordevelopers/user/UserMapper.java
  src/main/java/org/thisdote/communityfordevelopers/user/UserService.java
  src/main/resources/org/thisdote/communityfordevelopers/article/ArticleMapper.xml
  src/main/resources/org/thisdote/communityfordevelopers/user/UserMapper.xml
  src/test/java/org/thisdote/communityfordevelopers/user/UserTest.java
Labels: bug, enhancement

#30 [Hotfix] BeanCreationException 문제 해결(UserMapper.xml)
  src/main/resources/org/thisdote/communityfordevelopers/user/UserMapper.xml
Labels: bug

#31 [Feature] 활성화 상태 별 스터디 그룹 조회 쿼리 작성 및 테스트 코드 작성
  src/main/java/org/thisdote/communityfordevelopers/studygroup/StudyGroupMapper.java
  src/main/java/org/thisdote/communityfordevelopers/studygroup/StudyGroupService.java
  src/main/resources/org/thisdote/communityfordevelopers/studygroup/StudyGroupMapper.xml
  src/test/java/org/thisdote/communityfordevelopers/studygroup/StudyGroupTests.java
Labels: enhancement

#32 [Feature] 스터디그룹 유형별 조회 기능
  src/main/java/org/thisdote/communityfordevelopers/studygroup/SearchStudyGroupTypeEnum.java
  src/main/java/org/thisdote/communityfordevelopers/studygroup/StudyGroupMapper.java
  src/main/java/org/thisdote/communityfordevelopers/studygroup/StudyGroupService.java
  src/main/resources/org/thisdote/communityfordevelopers/studygroup/StudyGroupMapper.xml
  src/test/java/org/thisdote/communityfordevelopers/article/ArticleTest.java
  src/test/java/org/thisdote/communityfordevelopers/studygroup/StudyGroupTests.java
Labels: enhancement

#34 [Feature] 회원별 댓글 조회 기능
  src/main/java/org/thisdote/communityfordevelopers/reply/ReplyMapper.java
  src/main/java/org/thisdote/communityfordevelopers/reply/ReplyService.java
  src/main/resources/org/thisdote/communityfordevelopers/reply/ReplyMapper.xml
  src/test/java/org/thisdote/communityfordevelopers/reply/ReplyTests.java
Labels: enhancement

#43 [Feature/crud blacklist] 블랙리스트관련 command 작성완료(+ 댓글관련 Entity 작성) 및 html 추가, build에 thymeleaf 추가
  build.gradle
  src/main/java/org/thisdote/communityfordevelopers/CommunityForDevelopersApplication.java
  src/main/java/org/thisdote/communityfordevelopers/article/query/ArticleDTO.java
  src/main/java/org/thisdote/communityfordevelopers/blacklist/command/controller/BlackListController.java
  src/main/java/org/thisdote/communityfordevelopers/blacklist/command/entity/BlackList.java
  src/main/java/org/thisdote/communityfordevelopers/blacklist/command/repository/BlackListRepository.java
  src/main/java/org/thisdote/communityfordevelopers/blacklist/command/service/BlackListCommandService.java
  src/main/java/org/thisdote/communityfordevelopers/blacklist/dto/BlackListDTO.java
  src/main/java/org/thisdote/communityfordevelopers/blacklist/query/BlackListMapper.java
  src/main/java/org/thisdote/communityfordevelopers/blacklist/query/BlackListService.java
  src/main/java/org/thisdote/communityfordevelopers/main/MainController.java
  src/main/java/org/thisdote/communityfordevelopers/reply/command/controller/ReplyController.java
  src/main/java/org/thisdote/communityfordevelopers/reply/command/entity/Reply.java
  src/main/java/org/thisdote/communityfordevelopers/reply/command/repository/ReplyRepository.java
  src/main/java/org/thisdote/communityfordevelopers/reply/command/service/ReplyCommandService.java
  src/main/java/org/thisdote/communityfordevelopers/reply/dto/ReplyDTO.java
  src/main/java/org/thisdote/communityfordevelopers/reply/query/ReplyMapper.java
  src/main/java/org/thisdote/communityfordevelopers/reply/query/ReplyService.java
  src/main/resources/org/thisdote/communityfordevelopers/article/query/ArticleMapper.xml
  src/main/resources/org/thisdote/communityfordevelopers/blacklist/query/BlacklistMapper.xml
  src/main/resources/org/thisdote/communityfordevelopers/reply/query/ReplyMapper.xml
  src/main/resources/templates/delete.html
  src/main/resources/templates/detail.html
  src/main/resources/templates/list.html
  src/main/resources/templates/main.html
  src/main/resources/templates/modify.html
  src/main/resources/templates/regist.html
  src/test/java/org/thisdote/communityfordevelopers/blacklist/command/BlackListCommandTests.java
  src/test/java/org/thisdote/communityfordevelopers/blacklist/query/BlackListTest.java
  src/test/java/org/thisdote/communityfordevelopers/reply/query/ReplyTests.java
Labels: enhancement

#50 [Feature] 게시글 입력 삭제
  src/main/java/org/thisdote/communityfordevelopers/article/command/ArticleController.java
  src/main/java/org/thisdote/communityfordevelopers/article/command/ArticleEntity.java
  src/main/java/org/thisdote/communityfordevelopers/article/command/ArticleRepository.java
  src/main/java/org/thisdote/communityfordevelopers/article/command/ArticleService1.java
  src/main/java/org/thisdote/communityfordevelopers/article/command/entity/ArticleEntity.java
  src/main/java/org/thisdote/communityfordevelopers/article/dto/ArticleDTO.java
  src/main/java/org/thisdote/communityfordevelopers/studygroup_member/command/entity/StudyGroupMemberIdClass.java
  src/test/java/org/thisdote/communityfordevelopers/article/command/ArticleTest.java
Labels: enhancement

#53 [Feature][Bug Fix] 신고 댓글, 게시글
  src/main/java/org/thisdote/communityfordevelopers/article/command/ArticleEntity.java
  src/main/java/org/thisdote/communityfordevelopers/article/command/ArticleService1.java
  src/main/java/org/thisdote/communityfordevelopers/reported_reply/command/ReportedReplyEntity.java
  src/main/java/org/thisdote/communityfordevelopers/reported_reply/command/ReportedReplyRepository.java
  src/main/java/org/thisdote/communityfordevelopers/reported_reply/command/ReportedReplyService1.java
  src/test/java/org/thisdote/communityfordevelopers/article/command/ArticleTest.java
  src/test/java/org/thisdote/communityfordevelopers/reported_reply/command/ReportedReplyTest.java
Labels: bug, enhancement

#57 [Feature] 스터디그룹 멤버 생성(등록)/수정/삭제 기능
  src/main/java/org/thisdote/communityfordevelopers/studygroup_member/command/service/StudyGroupMemberCommandService.java
  src/test/java/org/thisdote/communityfordevelopers/studygroup_member/command/StudyGroupMemberCommandTests.java
Labels: enhancement

#61 [Feature/crud reply] reply CRUD 코드 작성
  src/main/java/org/thisdote/communityfordevelopers/CommunityForDevelopersApplication.java
  src/main/java/org/thisdote/communityfordevelopers/blacklist/command/entity/BlackListEntity.java
  src/main/java/org/thisdote/communityfordevelopers/reply/command/controller/ReplyController.java
  src/main/java/org/thisdote/communityfordevelopers/reply/command/entity/Reply.java
  src/main/java/org/thisdote/communityfordevelopers/reply/command/service/ReplyCommandService.java
  src/main/java/org/thisdote/communityfordevelopers/reply/query/ReplyMapper.java
  src/main/java/org/thisdote/communityfordevelopers/reply/query/ReplyService.java
  src/test/java/org/thisdote/communityfordevelopers/reply/command/ReplyCommandTests.java
Labels: enhancement

#63 [Feature] 신고된 게시글 추가
  src/main/java/org/thisdote/communityfordevelopers/reported_article/command/entity/ReportedArticleEntity.java
  src/main/java/org/thisdote/communityfordevelopers/reported_article/command/repository/ReportedArticleRepository.java
  src/main/java/org/thisdote/communityfordevelopers/reported_article/command/service/ReportedArticleCommandService.java
  src/main/java/org/thisdote/communityfordevelopers/reported_article/dto/ReportedArticleDTO.java
  src/main/java/org/thisdote/communityfordevelopers/user/command/service/UserCommandService.java
  src/test/java/org/thisdote/communityfordevelopers/reported_article/command/service/ReportedArticleCommandServiceTest.java
Labels: enhancement

#70 [Feature] studygroup , inquiry Command 작업
  build.gradle
  src/main/java/org/thisdote/communityfordevelopers/CommunityForDevelopersApplication.java
  src/main/java/org/thisdote/communityfordevelopers/article/ArticleMapperService.java
  src/main/java/org/thisdote/communityfordevelopers/inquiry/command/entity/InquiryEntity.java
  src/main/java/org/thisdote/communityfordevelopers/inquiry/command/repository/InquiryCommandRepository.java
  src/main/java/org/thisdote/communityfordevelopers/inquiry/command/service/InquiryCommandService.java
  src/main/java/org/thisdote/communityfordevelopers/inquiry/dto/InquiryCommandDTO.java
  src/main/java/org/thisdote/communityfordevelopers/reported_article/ReportedArticle.java
  src/main/java/org/thisdote/communityfordevelopers/reported_reply/command/ReportedReplyService1.java
  src/main/java/org/thisdote/communityfordevelopers/reported_reply/dto/ReportedReplyDTO.java
  src/main/java/org/thisdote/communityfordevelopers/reported_reply/query/ReportedReplyMapper.java
  src/main/java/org/thisdote/communityfordevelopers/reported_reply/query/ReportedReplyService.java
  src/main/java/org/thisdote/communityfordevelopers/studygroup/command/entity/StudyGroupEntity.java
  src/main/java/org/thisdote/communityfordevelopers/studygroup/command/repository/StudyGroupRepository.java
  src/main/java/org/thisdote/communityfordevelopers/studygroup/command/service/StudyGroupCommandService.java
  src/main/java/org/thisdote/communityfordevelopers/studygroup/dto/StudyGroupCommandDTO.java
  src/main/java/org/thisdote/config/MybatisConfiguration.java
  src/main/resources/org/thisdote/communityfordevelopers/studygroup/query/StudyGroupMapper.xml
  src/test/java/org/thisdote/communityfordevelopers/inquiry/command/InquiryCommandTests.java
  src/test/java/org/thisdote/communityfordevelopers/reported_article/query/ReportedArticleTest.java
  src/test/java/org/thisdote/communityfordevelopers/reported_reply/command/ReportedReplyTest.java
  src/test/java/org/thisdote/communityfordevelopers/reported_reply/query/ReportedReplyTest.java
  src/test/java/org/thisdote/communityfordevelopers/studygroup/command/StudyGroupCommandTests.java
Labels: enhancement
